# Generated by Django 5.0.1 on 2025-11-16 19:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_equipement', models.CharField(max_length=255)),
                ('partition', models.CharField(max_length=255)),
                ('etat', models.CharField(default='actuel', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HardwareIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('nom_de_equipement', models.CharField(max_length=255)),
                ('partition', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_de_serie', models.CharField(blank=True, max_length=255, null=True)),
                ('equipement_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('anomalie_observee', models.TextField(blank=True, null=True)),
                ('action_realisee', models.TextField(blank=True, null=True)),
                ('piece_de_rechange_utilisee', models.TextField(blank=True, null=True)),
                ('etat_de_equipement_apres_intervention', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('duree_arret', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hardware_incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('simulateur', models.BooleanField(default=False)),
                ('salle_operationnelle', models.BooleanField(default=False)),
                ('server', models.CharField(blank=True, max_length=255, null=True)),
                ('game', models.CharField(blank=True, max_length=255, null=True)),
                ('partition', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('exercice', models.CharField(blank=True, max_length=255, null=True)),
                ('secteur', models.CharField(blank=True, max_length=255, null=True)),
                ('position_STA', models.CharField(blank=True, max_length=255, null=True)),
                ('position_logique', models.CharField(blank=True, max_length=255, null=True)),
                ('type_d_anomalie', models.CharField(blank=True, max_length=255, null=True)),
                ('indicatif', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_radar', models.CharField(blank=True, max_length=255, null=True)),
                ('FL', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('code_SSR', models.CharField(blank=True, max_length=255, null=True)),
                ('sujet', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'software_incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('technicien', 'Technicien'), ('ingenieur', 'Ingénieur'), ('chefdep', 'Chef de Département'), ('superuser', 'Super Utilisateur')], default='technicien', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('anomaly', models.TextField()),
                ('analysis', models.TextField()),
                ('conclusion', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('software_incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.softwareincident')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
